# Permalinks
permalink:        pretty

# Setup
title:            BuildMill
tagline:          
url:              http://buildmill.org
paginate:         1
baseurl:          /
author:
  name:           Mark Otto
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
